# Generated by Django 4.0 on 2021-12-27 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='decorations',
        ),
    ]
