# Generated by Django 4.0 on 2021-12-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_fish_decorations'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fish',
            name='age',
            field=models.IntegerField(default='10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fish',
            name='price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
